# Generated by Django 5.2 on 2025-04-17 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuarios_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(upload_to='productos/')),
                ('category', models.CharField(choices=[('laptop', 'Laptop'), ('celular', 'Celular')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.producto')),
            ],
            bases=('users.producto',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.producto')),
                ('type', models.CharField(choices=[('gaming', 'Gaming'), ('hogar', 'Hogar'), ('escuela', 'Escuela')], max_length=20)),
            ],
            bases=('users.producto',),
        ),
    ]
