# Generated by Django 5.2 on 2025-04-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='producto_ptr',
        ),
        migrations.DeleteModel(
            name='Celular',
        ),
        migrations.DeleteModel(
            name='Laptop',
        ),
    ]
