# Generated by Django 5.2 on 2025-04-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_laptop_producto_ptr_delete_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
