# Generated by Django 5.2 on 2025-04-25 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_orden_detalleorden_tarjeta_orden_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='tarjeta',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
