# Generated by Django 5.2 on 2025-04-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_producto_stock_alter_tarjeta_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='serial',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
