# Generated by Django 5.2 on 2025-04-25 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_tarjeta_serial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
