# Generated by Django 5.2 on 2025-04-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
