# Generated by Django 5.2 on 2025-04-30 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_tarjeta_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='fecha',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='La fecha debe tener el formato MM/YYYY', regex='^(0[1-9]|1[0-2])\\/\\d{4}$')]),
        ),
    ]
