# Generated by Django 5.2 on 2025-04-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_tarjeta_fecha_tarjeta_fecha_expiracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='fecha_expiracion',
        ),
    ]
