# Generated by Django 5.2 on 2025-04-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_tarjeta_fecha_expiracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='fecha_expiracion',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
