# Generated by Django 5.2 on 2025-04-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_tarjeta_fecha_expiracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='monto',
            new_name='saldo',
        ),
    ]
