# Generated by Django 5.2 on 2025-05-03 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_monto_tarjeta_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='phone_number',
        ),
    ]
